#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/apache2
- name: Start apache service manualmente (sin systemd)
  shell: nohup apache2ctl -D FOREGROUND > /var/log/apache_foreground.log 2>&1 &

- name: Restart apache2 manualmente (sin systemd)
  ansible.builtin.shell: apache2ctl -k restart
