FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y openssh-server iproute2 && \
    mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["tail", "-f", "/dev/null"]